# Copyright The eha-sdk Contributors

[package]
name = "eha-tool"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
eha-sdk = { path = "../.." }
rustyline = { version = "18.0.1", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["float_roundtrip", "raw_value"] }
shlex = "2.0.1"
tiny_http = "0.12"
